version: '3'

services:
  www:
    image: nginx
    volumes:
      - .:/var/www:delegated
      - .docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${EXTERNAL_WWW_PORT:-80}:80
    depends_on:
      - php
    networks:
      - meetup-dev
  php:
    build:
      context: .docker/dev/php
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    ports:
      - ${EXTERNAL_PHP_PORT:-9000}:9000
    working_dir: /var/www
    user: ${CURRENT_UID:-1000}
    environment:
      - DOCKER=1
      - PHP_IDE_CONFIG=serverName=meetup.local
    volumes:
      - .docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - .:/var/www:delegated
    networks:
      - meetup-dev
    depends_on:
      - database
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  redis:
    image: 'redis:6'
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - ${EXTERNAL_REDIS_PORT:-6379}:6379
    volumes:
      - ./storage/redis:/data
    networks:
      - meetup-dev
  node:
    image: "node:14"
    tty: true
    ports:
      - ${EXTERNAL_NODE_PORT:-3000}:3000
    working_dir: /src
    volumes:
      - ./:/src
    networks:
      - meetup-dev
  database:
    image: postgres:14
    environment:
      - PGPASSWORD=${DOCKER_DEV_DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DOCKER_DEV_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_DEV_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DEV_DB_PASSWORD}
    ports:
      - ${DOCKER_DEV_DB_EXTERNAL_PORT:-5432}:5432
    volumes:
      - ./meetup-pgsql-data:/var/lib/postgresql/data
    networks:
      - meetup-dev
    restart: unless-stopped
networks:
  meetup-dev:
    driver: bridge
